name: ghcr github action
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: vcc-azure-ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
          ls -l 
          cd docker
          ls -l
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker} 
          mkdir -p $DOCKER_CONFIG/cli-plugins
          # curl -SL https://github.com/docker/compose/releases/download/v2.33.0/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
          curl -SL https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
          chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
          docker compose version
          docker compose -f run_test/compose.yml build --no-cache database
