name: ghcr github action
on: [push]
jobs:
  pull-request-review:
    runs-on: vcc-azure-ubuntu
    permissions:
      contents: read
      packages: write
      id-token: write
      pull-requests: read
      repository-projects: read
      statuses: read
      checks: read
      issues: read
      actions: read
    outputs:
      output1: ${{ steps.prr.outputs.test }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Pull Request Review
        id: prr
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo "test=$(gh pr view $PR_NUMBER --json files --jq '.files.[0].path')" >> "$GITHUB_OUTPUT"

  test_job:
    runs-on: vcc-azure-ubuntu
    needs: pull-request-review
    steps:
      - env:
          OUTPUT1: ${{needs.pull-request-review.outputs.output1}}
        run: echo "$OUTPUT1"
          
  # publish-database-docker-image:
  #   runs-on: vcc-azure-ubuntu
  #   permissions:
  #     contents: read
  #     packages: write
  #     id-token: write
  #   steps:
  #     - uses: actions/checkout@v2
      
  #     - name: Set up Docker
  #       uses: docker/setup-docker-action@v4
      
      
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v3.4.0
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Build and push test_database Docker image
  #       run: |
  #         docker compose -f docker/run_test/compose_builder.yml build --no-cache database
  #         docker push ghcr.io/volvo-cars/test_odin_database:latest


  # publish-backend-docker-image:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #     id-token: write
  #   steps:
  #     - env:
  #         OUTPUT1: ${{needs.job1.outputs.output1}}
  #     - name: Set up Docker
  #       uses: docker/setup-docker-action@v4

  #     - uses: actions/checkout@v2
      
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v3.4.0
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Build and push test_backend Docker image
  #       run: |
  #         docker compose -f docker/run_test/compose_builder.yml build --no-cache backend
  #         docker push ghcr.io/volvo-cars/test_odin_backend:latest
