name: Manual ODIN App Deployment
on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        description: Environment
        options:
          - development
          - testing
