on:
  workflow_call:
      inputs:
        environment:
          required: true
          type: string
        ref:
          required: true
          type: string
      secrets:
        client-id:
          required: true
        tenant-id:
          required: true
        subscription-id:
          required: true
        terraform-token:
          required: true

permissions:
  id-token: write # Require write permission to Fetch an OIDC token. 
  contents: read
      
jobs:
  infra:
    name: Infrastructure Deployment
    runs-on: vcc-azure-ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          cli_config_credentials_token: ${{ terraform-token }}
