on:
  workflow_call:
    inputs:
        if_test_backend:
          required: true
          type: string
          default: 0
  merge_group:

name: Reusable template Test Backend

jobs:
  job:
    if: ${{ inputs.if_test_backend }}
    name: Test Backend
    runs-on: vcc-azure-ubuntu
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      
      - uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Backend Test
        run: |
          docker compose -f 'docker/run_test/compose.yml' up -d database
          docker compose -f 'docker/run_test/compose.yml' up backend --abort-on-container-exit --exit-code-from backend
          docker_exit=$?
          echo $docker_exit
          docker compose -f 'docker/run_test/compose.yml' rm -s -f backend
          docker compose -f 'docker/run_test/compose.yml' rm -s -f database
