on:
  workflow_call:
      inputs:
        environment:
          required: true
          type: string
        ref:
          required: true
          type: string
      secrets:
        client-id:
          required: true
        tenant-id:
          required: true
        subscription-id:
          required: true
        terraform-token:
          required: true

env:
  TF_CLOUD_ORGANIZATION: Sikalokym
  TF_CLOUD_PROJECT: Odin
  TF_WORKSPACE: ${{ inputs.environment }}
  ARM_CLIENT_ID: ${{ secrets.client-id }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.subscription-id }}
  ARM_TENANT_ID:  ${{ secrets.tenant-id }}

permissions:
  id-token: write # Require write permission to Fetch an OIDC token. 
  contents: read
      
jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: vcc-azure-ubuntu-latest
    # env:
    #   TF_CLOUD_ORGANIZATION: Sikalokym
    #   TF_CLOUD_PROJECT: Odin
    #   TF_WORKSPACE: ${{ inputs.environment }}
    #   ARM_CLIENT_ID: ${{ secrets.client-id }}
    #   ARM_SUBSCRIPTION_ID: ${{ secrets.subscription-id }}
    #   ARM_TENANT_ID:  ${{ secrets.tenant-id }}
      
    # environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          cli_config_credentials_token: ${{ secrets.terraform-token }}

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -var-file tfvars/dev.tfvars -input=false -out=odin.${{ inputs.environment }}.tfplan

      - name: Upload Terraform Plan for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/odin.${{ inputs.environment }}.tfplan
  
  terraform-apply:
    name: Terraform Apply
    runs-on: vcc-azure-ubuntu-latest
    # env:
    #   TF_CLOUD_ORGANIZATION: Sikalokym
    #   TF_CLOUD_PROJECT: Odin
    #   TF_WORKSPACE: ${{ inputs.environment }}
    #   ARM_CLIENT_ID: ${{ secrets.client-id }}
    #   ARM_SUBSCRIPTION_ID: ${{ secrets.subscription-id }}
    #   ARM_TENANT_ID:  ${{ secrets.tenant-id }}
      
    # environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          cli_config_credentials_token: ${{ secrets.terraform-token }}
