on: [push]

jobs:
  job:
    name: test backend
    runs-on: vcc-azure-ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Random Password Generator
        id: generated-password
        uses: aammirmirza/RandomPasswordGenerator@1.2
        with:
          length: 20
      
      - run: echo "${{ steps.generated-password.outputs.password }}"
        shell: bash

      - name: Create database instance
        run: |
          ${{ steps.generated-password.outputs.password }} > docker/database_admin
          docker compose -f 'docker\compose.yml' up -d --build 'database'
          
