on: [push]

jobs:
  job:
    name: test backend
    runs-on: vcc-azure-ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Random Password Generator
      #   id: generated-password
      #   uses: aammirmirza/RandomPasswordGenerator@1.2
      #   with:
      #     length: 20
      
      # - run: echo "sdfgdsfg3454!" > docker/database_admin
      #   shell: bash

      - name: Create database instance
        run: |
          echo $HOME
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
          echo $DOCKER_CONFIG
          ls -l /home/runner
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
          mkdir -p $DOCKER_CONFIG/cli-plugins
          curl -SL https://github.com/docker/compose/releases/download/v2.33.0/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
          ls -l /home/runner/.docker
          # docker build -f ./docker/database/database.Dockerfile . -t odin_database --secret id=sa_password,src=./docker/database_admin
          # docker container run --rm -p 1433:1433 --name odin_database_cntr -d odin_database
          # id
          # sudo apt-get update
          # sudo apt-get install docker-compose-plugin
          
