on:
  push:
    branches: 
      - 'main'
      - 'test'
      - 'dev'
    paths: 
      - 'frontend/**'
      - 'backend/**'

name: ODIN deployment

run-name: Deploy to ${{ github.ref == 'refs/heads/dev' && 'Development' ||
                        github.ref == 'refs/heads/test' && 'Testing' }} environment

jobs:
  job:
    name: Deploy to ${{ github.ref == 'refs/heads/dev' && 'Development' ||
                        github.ref == 'refs/heads/test' && 'Testing' }}
    uses: ./.github/workflows/reusable_odin_deployment.yml
    with:
      environment: ${{ github.ref == 'refs/heads/dev' && 'Development' ||
                       github.ref == 'refs/heads/test' && 'Testing' }}
      ref: ${{ github.ref }}
    secrets:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
