services:
  database:
    image: "test_odin_database"
    build:
      context: ..
      dockerfile: run_test/database/database.Dockerfile
      secrets:
        - sa_password
    container_name: test_odin_database
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD_FILE: /run/secrets/sa_password
      DOCKER_BUILDKIT: 1
    secrets:
      - sa_password
  
  backend:
    image: "test_odin_backend"
    build:
      context: ..
      dockerfile: run_test/backend/backend.Dockerfile
    container_name: test_odin_backend
    environment:
      DB_CONNECTION_STRING: "Driver={ODBC Driver 18 for SQL Server};Server=test_odin_database;Database=odin;Authentication=SqlPassword;Encrypt=no;TrustServerCertificate=Yes;Connection Timeout=60;"
      SQL_DB_UID: "sa"
      SQL_DB_PWD: "M1y9k8o3l1a2a!"
    volumes:
      - ../../backend:/app
      - ./backend/start_backend_test.sh:/usr/start_backend_test.sh
      - ./backend/odin_database:/odin_database
    secrets:
      - sa_password
    entrypoint: ["bash", "/usr/start_backend_test.sh" ]

secrets:
  sa_password:
    file: database/database_admin


# Manual run:
# docker compose -f docker/compose.yml build --no-cache
# docker compose -f docker/compose.yml up -d database

# docker compose -f 'docker\compose.yml' up -d --build 'database' 
# docker build -f .\docker\database\database.Dockerfile . -t odin_database --secret id=sa_password,src=.\docker\database_admin
# docker container run --rm -p 1433:1433 --network docker_default --name test_odin_database -d test_odin_database
# docker container run -it -v .\backend:/app --env DB_CONNECTION_STRING="DSN=MSSQLServerDatabase;Database=odin;Encrypt=yes;Connection Timeout=30;" --env SQL_DB_UID="sa" --env SQL_DB_PWD="M1y9k8o3l1a2a!" --network docker_default --name test_odin_backend test_odin_backend bash


# docker container run -it --name odin_backend_debug -v .\backend:/app --env DB_CONNECTION_STRING="DSN=MSSQLServerDatabase;Database=odin;Uid=sa;Pwd=;Encrypt=yes;Connection Timeout=30;" --publish 5000:50505 --network docker_default odin_backend bash
# docker container run -it --rm -p 8080:8080 --name odin_frontend_debug --network docker_default -v .\frontend:/app odin_frontend bash

# docker container run -it --name odin_backend_debug -v .\backend:/app --env DB_CONNECTION_STRING="Driver={ODBC Driver 18 for SQL Server};Server=;Database=;Uid=pmt_db_service;Pwd=;Authentication=SqlPassword;Encrypt=no;TrustServerCertificate=no;Connection Timeout=60;" --publish 5000:50505 --network docker_default odin_backend bash